=== git-akram/coUps-WS/src/main/webapp/WEB-INF/xsd/RechercheVoisinsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<tns:schema xmlns:tns="http://www.w3.org/2001/XMLSchema" xmlns="http://coUps/RechercheVoisinsSchema" targetNamespace="http://coUps/RechercheVoisinsSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<tns:element name="rechercheVoisinsRequest">
		<tns:complexType>
			<tns:sequence>
				<tns:element type="tns:string" name="email" maxOccurs="1" minOccurs="1"/>
				<tns:element type="tns:integer" name="distance" maxOccurs="1" minOccurs="1"/>
			</tns:sequence>
		</tns:complexType>		
	</tns:element>
	<tns:element name="rechercheVoisinsResponse">
		<tns:complexType>
			<tns:sequence>
				<tns:element name="voisin" maxOccurs="unbounded" minOccurs="0">
					<tns:complexType>
						<tns:sequence>
							<tns:element type="tns:string" name="nom" maxOccurs="1" minOccurs="1"/>
							<tns:element type="tns:string" name="prenom" maxOccurs="1" minOccurs="1"/>
							<tns:element type="tns:string" name="email" maxOccurs="1" minOccurs="1"/>
							<tns:element type="tns:string" name="adresse" maxOccurs="1" minOccurs="1"/>
							<tns:element type="tns:integer" name="distance" maxOccurs="1" minOccurs="1"/>
							<tns:element name="coordonnees" maxOccurs="1" minOccurs="1">
								<tns:complexType>
									<tns:sequence>
										<tns:element type="tns:double" name="longitude" maxOccurs="1" minOccurs="1"/>
										<tns:element type="tns:double" name="latitude" maxOccurs="1" minOccurs="1"/>
									</tns:sequence>
								</tns:complexType>
							</tns:element>
						</tns:sequence>
					</tns:complexType>
				</tns:element>
			</tns:sequence>
		</tns:complexType>		
	</tns:element>
</tns:schema>

=== git-akram/coUps-WS/src/main/resources/RechercheVoisinsResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<rechercheVoisinsResponse
			xmlns="http://coUps/RechercheVoisinsSchema"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://coUps/RechercheVoisinsSchema rechercheVoisinsSchema.xsd">
	<voisin>
    	<nom>user1</nom>
    	<prenom>prenom1</prenom>
    	<email>user1@exemple.com</email>
    	<adresse>31 rue toulouse</adresse>
  	</voisin>
  	<voisin>
	    <nom>user2</nom>
	    <prenom>prenom2</prenom>
	    <email>user2@exemple.com</email>
	    <adresse>40 rue toulouse</adresse>
  	</voisin>
</rechercheVoisinsResponse>
